### ISSUE TITLE
Implement a CI pipeline

### ISSUE THREAD

**Issue by xlc** [type-metadata/type-metadata#10]
For CI we mainly need it to check for the following:

- [ ] All tests should pass (`cargo test`) and also the derive tests (`cargo test --feature derive`)
- [ ] Formatting should be correct: `cargo fmt`
- [ ] Wasm target should build correctly

**Comment by shaunxw** [comment]
Just a reminder for wasm target test: I've created `derive_tests_no_std` crate under `test_suite` in #16 , we could test if `no_std` env works by trying to build it. It cannot share the same workspace with other crates, due to the custom defined lang items. In the CI script we need to `cd` to `test_suite/derive_tests_no_std` directory and then run the build command.
